### ISSUE TITLE
`npm-lazy-mirror` global command broken on Windows

### ISSUE THREAD

**Issue by robatron** [hpcloud/npm-lazy-mirror#14]
```
$ npm-lazy-mirror

module.js:340
    throw err;
          ^
Error: Cannot find module 'c:\Users\rmcguir\AppData\Roaming\npm\node_modules\npm-lazy-mirror\lib\node_modules\npm-lazy-mirror\server.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by robatron** [comment]
Just checked; This appears to work on Linux, so this likely a Windows-specific issue. Looks like this issue has something to do with how y'all are [constructing the absolute path to the bin script](https://github.com/ActiveState/npm-lazy-mirror/blob/master/bin/npm-lazy-mirror#L7). 

(Linux constructs from the system-level bin script, and Windows constructs from the package-level bin script.)

**Comment by robatron** [comment]
Dug into this a bit more: 

This is happening because on Unix, global binaries are a symlink from `/usr/bin/$PACKAGE` -> `/usr/lib/node_modules/$PACKAGE/bin/$PACKAGE`, so [`$DIR`](https://github.com/ActiveState/npm-lazy-mirror/blob/master/bin/npm-lazy-mirror#L7) will be `/usr/bin`, but on Windows, it'll be `$HOME/AppData/Roaming/npm/node_modules/npm-lazy-mirror/bin`.

This means that on Unix, the bin command will (correctly) be 

```
node /usr/bin/../lib/node_modules/npm-lazy-mirror/server.js
```

But on Windows, it will be 

```
node $HOME/AppData/Roaming/npm/node_modules/npm-lazy-mirror/bin/../lib/node_modules/npm-lazy-mirror/server.js
```

Reference: [npm-folders](https://www.npmjs.org/doc/files/npm-folders.html)
